apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  restartPolicy: Never
  containers:
  - image: ubuntu
    name: ubuntu-container
    command: [ "sleep", "600" ]
    volumeMounts:
    - mountPath: /data/application
      name: mypvc-volume
  volumes:
  - name: mypvc-volume
    persistentVolumeClaim:
      claimName: mypvc
