apiVersion: apps/v1
kind: Deployment
metadata:
  name: pageview
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pageview
  template:
    metadata:
      labels:
        app: pageview
    spec:
      containers:
      - name: pageview
        image: docker.io/nisburgh/pageview:v1.0
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 10
      - name: ns
        image: nicolaka/netshoot
        tty: true
