apiVersion: v1
kind: Pod
metadata:
  name: pod-with-huge-resource-requirements
spec:
  containers:
    - name: container-with-huge-resource-requirements
      image: nginxinc/nginx-unprivileged
      resources:
        limits:
          memory: "128G"
          cpu: "1000"
        requests:
          memory: "64G"
          cpu: "500"
